### ISSUE TITLE
有token 也登不上去

### ISSUE THREAD

**Issue by nearxu** [Juliiii/React-Cnode#13]
401错误

**Comment by Juliiii** [comment]
401的话是cnode提供的api返回的，应该是未授权的意思，具体获取token
的方法是登进[https://cnodejs.org/](cnode)社区，然后在进入 **设置**，
最底部有token。

**Comment by nearxu** [comment]
非常感谢你的及时回复，我再看看，有可能是我之前测试的时候发帖被封号了。
