### ISSUE TITLE
，您好我是react新手，请教一些问题

### ISSUE THREAD

**Issue by zhangyuling37du** [Juliiii/React-Cnode#15]
看见您的项目，想问下你的项目有没有详解的，还有就是，在入口文件引入router 和store文件，路径都是对的，但是还是报错index.js:11 Uncaught ReferenceError: Router is not defined，是在哪里有配置路径么，还是。。。

**Comment by Juliiii** [comment]
@zhangyuling37du 1、暂时木有详解呢。

**Comment by Juliiii** [comment]
@zhangyuling37du 2、Router配置的路径应该在index.js里有写呢，引入Router的路径就是。至于报错。缺认是否真的引入了呢，有可能是大小写拼错了之类的小问题吧？
